### ISSUE TITLE
New KiCAD project format?

### ISSUE THREAD

**Issue by kaklik** [likeablob/rename-kicad-project#11]
Should it work for the new project format names like .kicad_pcb, .kicad_pro, .kicad_sch etc?

**Comment by likeablob** [comment]
Hi @kaklik 
Thanks for the heads up. I didn't even noticed the new format. I'm still on KiCad v5 stable.
https://docs.kicad.org/6.0/en/kicad/kicad.html

Since [this tool infers the project name based on a `.pro` file](https://github.com/likeablob/rename-kicad-project/blob/main/src/rename_kicad_project/manipulator.py#L42
),  the current version can't handle projects with the new format.   
But I think it's not so difficult to make things work. Let me see how it goes with v6.

**Comment by felixfilipi** [comment]
Hi, any update on this thread?

**Comment by likeablob** [comment]
Sry for the late response. #12 will resolve this issue. (Thanks to @markwal) 
And FYI, from KiCad 6.0, **now you can rename your project from `Save As` :tada: .**

![image](https://user-images.githubusercontent.com/46628917/218268340-11d41eef-bb6d-4fd3-aac2-a990d19ecfb5.png)
